### PR TITLE
Update perms for build dir

### PR DESCRIPTION
**Pull request by amouat**

### CODE REVIEW

**Comment by imjasonh** [comment]
Can we add an example like the one in https://github.com/chainguard-images/static/pull/24 to prove that it fixes the build issue?

It feels sort of weird to duplicate the example, but it would let us test for breaking changes in either go or static, and would be a useful example as a bonus.

**Comment by amouat** [comment]
Good plan. I'd like to know what the difference is though, so that we can recreate it locally.

**Comment by amouat** [comment]
Just ran a test and this doesn't seem to help in the case of the reported issue.

**Comment by jdolitsky** [comment]
closing since going to archive this repo

**Pull request closed without merging**
